# Generated by Django 6.0.1 on 2026-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_partition_message_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('sticker', 'Sticker'), ('external_task', 'External Task')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='ExternalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_odoo_user', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Response'), ('responded', 'Responded'), ('failed', 'Delivery Failed')], default='pending', max_length=20)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('responded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='external_task', to='chat.message')),
            ],
        ),
    ]
